"""add_processing_log_table

Revision ID: 0550c656dd00
Revises: 18e47cbf7a1e
Create Date: 2026-03-23 16:24:22.308850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0550c656dd00'
down_revision: Union[str, Sequence[str], None] = '18e47cbf7a1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recording_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('success', 'failed', 'skipped')", name='ck_processing_log_status'),
    sa.CheckConstraint("step IN ('ingest', 'librosa', 'clap', 'coverhunter')", name='ck_processing_log_step'),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_log_recording_id'), 'processing_log', ['recording_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_log_recording_id'), table_name='processing_log')
    op.drop_table('processing_log')
    # ### end Alembic commands ###
