"""initial schema

Revision ID: 18e47cbf7a1e
Revises: 
Create Date: 2026-03-23 14:35:18.111892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18e47cbf7a1e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('date_uncertain', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('cover_of', sa.Text(), nullable=True),
    sa.CheckConstraint("type IN ('original', 'cover', 'jam')", name='ck_songs_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('recordings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('source_path', sa.JSON(), nullable=False),
    sa.Column('audio_path', sa.Text(), nullable=True),
    sa.Column('start_offset_seconds', sa.Float(), nullable=True),
    sa.Column('end_offset_seconds', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.CheckConstraint("origin IN ('pretrimmed', 'vad_segment')", name='ck_recordings_origin'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recordings_session_id'), 'recordings', ['session_id'], unique=False)
    op.create_index(op.f('ix_recordings_song_id'), 'recordings', ['song_id'], unique=False)
    op.create_table('feature_timeseries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recording_id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(length=64), nullable=False),
    sa.Column('packed_values', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recording_id', 'feature_name')
    )
    op.create_index(op.f('ix_feature_timeseries_recording_id'), 'feature_timeseries', ['recording_id'], unique=False)
    op.create_table('segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recording_id', sa.Integer(), nullable=False),
    sa.Column('start_seconds', sa.Float(), nullable=False),
    sa.Column('end_seconds', sa.Float(), nullable=False),
    sa.Column('clap_embedding', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segments_recording_id'), 'segments', ['recording_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segments_recording_id'), table_name='segments')
    op.drop_table('segments')
    op.drop_index(op.f('ix_feature_timeseries_recording_id'), table_name='feature_timeseries')
    op.drop_table('feature_timeseries')
    op.drop_index(op.f('ix_recordings_song_id'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_session_id'), table_name='recordings')
    op.drop_table('recordings')
    op.drop_table('songs')
    op.drop_table('sessions')
    # ### end Alembic commands ###
