"""add_segment_librosa_columns

Revision ID: 210ed4a1b667
Revises: 0550c656dd00
Create Date: 2026-03-23 17:06:01.870258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '210ed4a1b667'
down_revision: Union[str, Sequence[str], None] = '0550c656dd00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segments', sa.Column('mean_rms', sa.Float(), nullable=True))
    op.add_column('segments', sa.Column('var_rms', sa.Float(), nullable=True))
    op.add_column('segments', sa.Column('mean_spectral_centroid', sa.Float(), nullable=True))
    op.add_column('segments', sa.Column('var_spectral_centroid', sa.Float(), nullable=True))
    op.add_column('segments', sa.Column('mean_chroma', sa.LargeBinary(), nullable=True))
    op.add_column('segments', sa.Column('var_chroma', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('segments', 'var_chroma')
    op.drop_column('segments', 'mean_chroma')
    op.drop_column('segments', 'var_spectral_centroid')
    op.drop_column('segments', 'mean_spectral_centroid')
    op.drop_column('segments', 'var_rms')
    op.drop_column('segments', 'mean_rms')
    # ### end Alembic commands ###
