import type { Recording, Session, SongDetail } from "./api";

export const MOCK_SONGS: SongDetail[] = [
  {
    id: 1,
    title: "Lady Monas Experience",
    slug: "Lady-Monas-Experience",
    song_type: "original",
    cover_of: null,
    recordings: [
      {
        id: 101,
        title: "Lady Monas Experience",
        origin: "pretrimmed",
        duration_seconds: 247,
        session_date: "2013-11-16",
        song_id: 1,
        song_title: "Lady Monas Experience",
        audio_path: null,
      },
      {
        id: 102,
        title: "Lady Monas Experience",
        origin: "pretrimmed",
        duration_seconds: 263,
        session_date: "2015-06-12",
        song_id: 1,
        song_title: "Lady Monas Experience",
        audio_path: null,
      },
      {
        id: 103,
        title: "Lady Monas Experience",
        origin: "pretrimmed",
        duration_seconds: 218,
        session_date: "2015-09-25",
        song_id: 1,
        song_title: "Lady Monas Experience",
        audio_path: null,
      },
    ],
  },
  {
    id: 2,
    title: "Blades",
    slug: "Blades",
    song_type: "original",
    cover_of: null,
    recordings: [
      {
        id: 201,
        title: "Blades",
        origin: "pretrimmed",
        duration_seconds: 312,
        session_date: "2014-03-08",
        song_id: 2,
        song_title: "Blades",
        audio_path: null,
      },
      {
        id: 202,
        title: "Blades",
        origin: "pretrimmed",
        duration_seconds: 298,
        session_date: "2016-05-14",
        song_id: 2,
        song_title: "Blades",
        audio_path: null,
      },
    ],
  },
  {
    id: 3,
    title: "Under The Bridge",
    slug: "Under-The-Bridge",
    song_type: "cover",
    cover_of: "Red Hot Chili Peppers",
    recordings: [
      {
        id: 301,
        title: "Under The Bridge",
        origin: "pretrimmed",
        duration_seconds: 268,
        session_date: "2015-02-21",
        song_id: 3,
        song_title: "Under The Bridge",
        audio_path: null,
      },
    ],
  },
  {
    id: 4,
    title: "El Cant Dels Ocells",
    slug: "El-Cant-Dels-Ocells",
    song_type: "cover",
    cover_of: "Traditional / Pau Casals",
    recordings: [
      {
        id: 401,
        title: "El Cant Dels Ocells",
        origin: "pretrimmed",
        duration_seconds: 184,
        session_date: "2016-09-22",
        song_id: 4,
        song_title: "El Cant Dels Ocells",
        audio_path: null,
      },
      {
        id: 402,
        title: "El Cant Dels Ocells",
        origin: "pretrimmed",
        duration_seconds: 201,
        session_date: "2017-01-15",
        song_id: 4,
        song_title: "El Cant Dels Ocells",
        audio_path: null,
      },
    ],
  },
];

export const MOCK_JAMS: SongDetail[] = [
  {
    id: 10,
    title: "Same Rain New Villages",
    slug: "Same-Rain-New-Villages",
    song_type: "jam",
    cover_of: null,
    recordings: [
      {
        id: 1001,
        title: "Same Rain New Villages",
        origin: "pretrimmed",
        duration_seconds: 1847,
        session_date: "2013-11-16",
        song_id: 10,
        song_title: "Same Rain New Villages",
        audio_path: null,
      },
    ],
  },
  {
    id: 11,
    title: "La Part Més Fosca",
    slug: "La-part-mes-fosca",
    song_type: "jam",
    cover_of: null,
    recordings: [
      {
        id: 1101,
        title: "La Part Més Fosca",
        origin: "pretrimmed",
        duration_seconds: 2340,
        session_date: "2012-12-07",
        song_id: 11,
        song_title: "La Part Més Fosca",
        audio_path: null,
      },
    ],
  },
  {
    id: 12,
    title: "Per Tres Acords No Està Mal",
    slug: "Per-tres-acords-no-esta-mal",
    song_type: "jam",
    cover_of: null,
    recordings: [
      {
        id: 1201,
        title: "Per Tres Acords No Està Mal",
        origin: "pretrimmed",
        duration_seconds: 1523,
        session_date: "2012-12-07",
        song_id: 12,
        song_title: "Per Tres Acords No Està Mal",
        audio_path: null,
      },
    ],
  },
  {
    id: 13,
    title: "Volia Un Tremolo",
    slug: "Volia-un-tremolo",
    song_type: "jam",
    cover_of: null,
    recordings: [
      {
        id: 1301,
        title: "Volia Un Tremolo",
        origin: "pretrimmed",
        duration_seconds: 987,
        session_date: "2012-12-07",
        song_id: 13,
        song_title: "Volia Un Tremolo",
        audio_path: null,
      },
    ],
  },
];

export const MOCK_SESSIONS: Session[] = [
  {
    id: 1,
    date: "2016-09-22",
    date_uncertain: false,
    notes: null,
    recording_count: 8,
  },
  {
    id: 2,
    date: "2016-01-17",
    date_uncertain: false,
    notes: null,
    recording_count: 5,
  },
  {
    id: 3,
    date: "2015-09-25",
    date_uncertain: false,
    notes: null,
    recording_count: 3,
  },
  {
    id: 4,
    date: "2015-06-12",
    date_uncertain: false,
    notes: null,
    recording_count: 4,
  },
  {
    id: 5,
    date: "2014-03-08",
    date_uncertain: false,
    notes: "ft manaswi",
    recording_count: 6,
  },
  {
    id: 6,
    date: "2013-11-16",
    date_uncertain: false,
    notes: null,
    recording_count: 7,
  },
  {
    id: 7,
    date: "2012-12-07",
    date_uncertain: false,
    notes: null,
    recording_count: 4,
  },
];

export const MOCK_SESSION_RECORDINGS: Record<number, Recording[]> = {
  6: [
    {
      id: 101,
      title: "Lady Monas Experience",
      origin: "pretrimmed",
      duration_seconds: 247,
      session_date: "2013-11-16",
      song_id: 1,
      song_title: "Lady Monas Experience",
      audio_path: null,
    },
    {
      id: 1001,
      title: "Same Rain New Villages",
      origin: "pretrimmed",
      duration_seconds: 1847,
      session_date: "2013-11-16",
      song_id: 10,
      song_title: "Same Rain New Villages",
      audio_path: null,
    },
  ],
  7: [
    {
      id: 1101,
      title: "La Part Més Fosca",
      origin: "pretrimmed",
      duration_seconds: 2340,
      session_date: "2012-12-07",
      song_id: 11,
      song_title: "La Part Més Fosca",
      audio_path: null,
    },
    {
      id: 1201,
      title: "Per Tres Acords No Està Mal",
      origin: "pretrimmed",
      duration_seconds: 1523,
      session_date: "2012-12-07",
      song_id: 12,
      song_title: "Per Tres Acords No Està Mal",
      audio_path: null,
    },
    {
      id: 1301,
      title: "Volia Un Tremolo",
      origin: "pretrimmed",
      duration_seconds: 987,
      session_date: "2012-12-07",
      song_id: 13,
      song_title: "Volia Un Tremolo",
      audio_path: null,
    },
  ],
};
